package team;

public enum TeamStats {
    GAMES_PLAYED, WINS, LOSSES, TIES, WIN_RATE, LOSS_RATE, RANK, 
    TOTAL_TOURNAMENTS_PLAYED, TOURNAMENT_WINS, 
    GOALS_FOR, GOALS_AGAINST, FACE_OFF_WIN_PERCENTAGE, SHOTS_AGAINST, SHOTS_FOR, REGULATION_WINS, REGULATION_PLUS_OVERTIME_WINS, SHOOTOUT_GAMES_WON, OVERTIME_LOSSES, GOALS_FOR_PER_GAMES_PLAYED, GOALS_AGAINST_PER_GAMES_PLAYED, SHOTS_FOR_PER_GAMES_PLAYED, SHOTS_AGAINST_PER_GAMES_PLAYED,
    GAMES_STARTED, COMPLETE_GAMES, SHUTOUTS, SAVES, SAVE_OPPORTUNITIES, INNINGS_PITCHED, RUNS_ALLOWED, EARNED_RUNS, HOME_RUNS_ALLOWED, HIT_BATSMEN, AT_BATS, RUNS, HITS, DOUBLES, TRIPLES, HOME_RUNS, RUN_BATTED_IN, WALKS, STRIKEOUTS, STOLEN_BASES, CAUGHT_STEALING
}
