package team;

public enum TeamStats {
    GAMES_PLAYED, WINS, LOSSES, TIES, WIN_RATE, LOSS_RATE, RANK, 
    TOTAL_TOURNAMENTS_PLAYED, TOURNAMENT_WINS, 
    GOALS_FOR, GOALS_AGAINST, FACE_OFF_WIN_PERCENTAGE, SHOTS_AGAINST, SHOTS_FOR, REGULATION_WINS, REGULATION_PLUS_OVERTIME_WINS, SHOOT_OUT_GAMES_WON, OVERTIME_LOSSES
}
